<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>XB1ControllerBatteryIndicator</RootNamespace>
    <AssemblyName>XB1ControllerBatteryIndicator</AssemblyName>
    <ApplicationIcon>Resources\logo_black.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.3.2" />
    <PackageReference Include="Caliburn.Micro" Version="5.0.258" />
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <Compile Include="IsCurrentLanguageConverter.cs" />
    <Compile Include="LocalizationExtension.cs" />
    <Compile Include="Localization\Strings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
    <Compile Include="Settings.cs" />
    <Compile Include="ShellHelpers.cs" />
    <Compile Include="Icons.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Icons.resx</DependentUpon>
    </Compile>
    <Compile Include="SystemTrayView.xaml.cs">
      <DependentUpon>SystemTrayView.xaml</DependentUpon>
    </Compile>
    <Compile Include="SystemTrayViewModel.cs" />
    <Compile Include="TranslationBindingProvider.cs" />
    <Compile Include="TranslationManager.cs" />
    <Compile Include="XboxController.cs" />
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Compile Include="App.xaml.cs">
      <DependentUpon>App.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Bootstrapper.cs" />
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Page Include="SystemTrayView.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icons.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Icons.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Localization\Strings.cs.resx" />
    <EmbeddedResource Include="Localization\Strings.da.resx" />
    <EmbeddedResource Include="Localization\Strings.es.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Localization\Strings.de.resx" />
    <EmbeddedResource Include="Localization\Strings.fr.resx" />
    <EmbeddedResource Include="Localization\Strings.hu.resx" />
    <EmbeddedResource Include="Localization\Strings.it.resx" />
    <EmbeddedResource Include="Localization\Strings.ja.resx" />
    <EmbeddedResource Include="Localization\Strings.ko.resx" />
    <EmbeddedResource Include="Localization\Strings.nl.resx" />
    <EmbeddedResource Include="Localization\Strings.pl.resx" />
    <EmbeddedResource Include="Localization\Strings.pt-br.resx" />
    <EmbeddedResource Include="Localization\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Localization\Strings.sv.resx" />
    <EmbeddedResource Include="Localization\Strings.uk-UA.resx" />
    <EmbeddedResource Include="Localization\Strings.ru.resx" />
    <EmbeddedResource Include="Localization\Strings.tr.resx" />
    <EmbeddedResource Include="Localization\Strings.zh-cn.resx" />
    <EmbeddedResource Include="Localization\Strings.zh-tw.resx" />
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="FodyWeavers.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Include="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\battery_unknown.ico" />
    <Resource Include="Resources\logo_black.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\battery_disconnected_four.ico" />
    <Resource Include="Resources\battery_disconnected_one.ico" />
    <Resource Include="Resources\battery_disconnected_three.ico" />
    <Resource Include="Resources\battery_disconnected_two.ico" />
    <Resource Include="Resources\battery_empty_four.ico" />
    <Resource Include="Resources\battery_empty_one.ico" />
    <Resource Include="Resources\battery_empty_three.ico" />
    <Resource Include="Resources\battery_empty_two.ico" />
    <Resource Include="Resources\battery_full_four.ico" />
    <Resource Include="Resources\battery_full_one.ico" />
    <Resource Include="Resources\battery_full_three.ico" />
    <Resource Include="Resources\battery_full_two.ico" />
    <Resource Include="Resources\battery_low_four.ico" />
    <Resource Include="Resources\battery_low_one.ico" />
    <Resource Include="Resources\battery_low_three.ico" />
    <Resource Include="Resources\battery_low_two.ico" />
    <Resource Include="Resources\battery_medium_four.ico" />
    <Resource Include="Resources\battery_medium_one.ico" />
    <Resource Include="Resources\battery_medium_three.ico" />
    <Resource Include="Resources\battery_medium_two.ico" />
    <Resource Include="Resources\battery_wired_four.ico" />
    <Resource Include="Resources\battery_wired_one.ico" />
    <Resource Include="Resources\battery_wired_three.ico" />
    <Resource Include="Resources\battery_wired_two.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="FodyWeavers.xml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\battery_disconnected_four-black.ico" />
    <Resource Include="Resources\battery_disconnected_one-black.ico" />
    <Resource Include="Resources\battery_disconnected_three-black.ico" />
    <Resource Include="Resources\battery_disconnected_two-black.ico" />
    <Resource Include="Resources\battery_empty_four-black.ico" />
    <Resource Include="Resources\battery_empty_one-black.ico" />
    <Resource Include="Resources\battery_empty_three-black.ico" />
    <Resource Include="Resources\battery_empty_two-black.ico" />
    <Resource Include="Resources\battery_full_four-black.ico" />
    <Resource Include="Resources\battery_full_one-black.ico" />
    <Resource Include="Resources\battery_full_three-black.ico" />
    <Resource Include="Resources\battery_full_two-black.ico" />
    <Resource Include="Resources\battery_low_four-black.ico" />
    <Resource Include="Resources\battery_low_one-black.ico" />
    <Resource Include="Resources\battery_low_three-black.ico" />
    <Resource Include="Resources\battery_low_two-black.ico" />
    <Resource Include="Resources\battery_medium_four-black.ico" />
    <Resource Include="Resources\battery_medium_one-black.ico" />
    <Resource Include="Resources\battery_medium_three-black.ico" />
    <Resource Include="Resources\battery_medium_two-black.ico" />
    <Resource Include="Resources\battery_unknown-black.ico" />
    <Resource Include="Resources\battery_wired_four-black.ico" />
    <Resource Include="Resources\battery_wired_one-black.ico" />
    <Resource Include="Resources\battery_wired_three-black.ico" />
    <Resource Include="Resources\battery_wired_two-black.ico" />
  </ItemGroup>

</Project>
