name: Windows build

on:
  push:
    branches:
      - best-of-forks
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore .\XB1ControllerBatteryIndicator\XB1ControllerBatteryIndicator.sln

      - name: Build Release
        run: msbuild .\XB1ControllerBatteryIndicator\XB1ControllerBatteryIndicator.sln /m /p:Configuration=Release /p:Platform="Any CPU" /v:minimal

      - name: Upload Release build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: XB1ControllerBatteryIndicator-1.3.2.0
          path: .\XB1ControllerBatteryIndicator\XB1ControllerBatteryIndicator\bin\Release\
          if-no-files-found: error
          retention-days: 30
